### ISSUE TITLE
Caused by: java.lang.RuntimeException: Unable to resolve var: com.gfredericks.debug-repl/wrap-debug-repl in this context

### ISSUE THREAD

**Issue by cch1** [gfredericks/debug-repl#7]
I'm seeing an exception loading debug repl.   This is the leiningen `:repl` profile:

``` Clojure
 :repl {:plugins [[cider/cider-nrepl "0.19.0"]]
        :dependencies [[com.gfredericks/debug-repl "0.0.9"]]
        :repl-options {:prompt (fn [ns] (str ns "> " ))
                       :init (set! *print-length* 50)
                       :nrepl-middleware [com.gfredericks.debug-repl/wrap-debug-repl]
                       }}

```
This occurs with leiningen 2.8.3

**Comment by gfredericks** [comment]
Looks like something changed in leiningen between 2.8.1 and 2.8.2.

The last item in [this list](https://github.com/technomancy/leiningen/blob/master/NEWS.md#282--2018-12-11) sounds related.

**Comment by gfredericks** [comment]
Judging by the docs linked there, I think the change I just pushed to [this branch](https://github.com/gfredericks/debug-repl/tree/nrepl-upgrade) is necessary, but it doesn't seem to be sufficient; I at least get a different error using that code.

**Comment by gfredericks** [comment]
The issues beyond changing the namespace names may be related to removing the nrepl-53 monkeypatch as described in #8.

**Comment by gfredericks** [comment]
Please try version `0.0.10` and let me know if you're still having issues.

**Comment by cch1** [comment]
This seems to have fixed the problem for me.
